# Generated by Django 2.1.5 on 2019-02-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190203_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksinfo',
            options={'permissions': (('read_item', 'Can read item'),)},
        ),
    ]
