# Generated by Django 2.1.3 on 2019-02-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='默认类别', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Siteinfo',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(default='图书置换平台', max_length=64)),
                ('announcement', models.TextField(blank=True, default='空', null=True)),
                ('guide', models.TextField(blank=True, default='空', null=True)),
            ],
        ),
    ]
