# Generated by Django 2.1.5 on 2019-02-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='announcement',
            field=models.TextField(blank=True, default='空', null=True, verbose_name='公告'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='guide',
            field=models.TextField(blank=True, default='空', null=True, verbose_name='指导'),
        ),
    ]
